--TABELLA DIPENDENTI
CREATE TABLE DIPENDENTI 
    ( 
     ID_DIPENDENTE   NUMBER (10) DEFAULT SEQ_DIPENDENTI.NEXTVAL  NOT NULL , 
     NOME            VARCHAR2 (50)  NOT NULL , 
     COGNOME         VARCHAR2 (50)  NOT NULL , 
     CODICE_FISCALE  VARCHAR2 (16)  NOT NULL , 
     DATA_NASCITA    DATE  NOT NULL , 
     TELEFONO        VARCHAR2 (12)  NOT NULL , 
     EMAIL           VARCHAR2 (100) , 
     DATA_ASSUNZIONE DATE  NOT NULL ,

     CONSTRAINT PK_DIPENDENTI PRIMARY KEY ( ID_DIPENDENTE ) ,
     CONSTRAINT UNIQUE_DIPENDENTI_CF UNIQUE ( CODICE_FISCALE ) ,
     CONSTRAINT FK_AUTISTI_DIPENDENTI FOREIGN KEY ( ID_DIPENDENTE ) 
	REFERENCES DIPENDENTI ( ID_DIPENDENTE ) 
    ) LOGGING 
;

--SPECIALIZZAZIONE TABELLA AUTISTI
CREATE TABLE AUTISTI 
    ( 
     ID_DIPENDENTE    NUMBER (10) NOT NULL , 
     PATENTE_NUMERO   VARCHAR2 (20) NOT NULL , 
     PATENTE_SCADENZA DATE NOT NULL ,
     CONSTRAINT PK_AUTISTI PRIMARY KEY ( ID_DIPENDENTE ),
     CONSTRAINT UNIQUE_AUTISTI_PATENTE UNIQUE ( PATENTE_NUMERO ),
     CONSTRAINT FK_DIPENDENTI FOREIGN KEY (ID_DIPENDENTI) 
        REFERENCES DIPENDENTI (ID_DIPENDENTE) 
    ) LOGGING ;


--TABELLA BIGLIETTI
CREATE TABLE BIGLIETTI 
    ( 
     CODICE_BIGLIETTO             NUMBER (10)  DEFAULT SEQ_BIGLIETTI.NEXTVAL NOT NULL , 
     PRENOTAZIONI_ID_PRENOTAZIONE NUMBER (10)  NOT NULL , 
     NUMERO_POSTO                 NUMBER (3)  NOT NULL , 
     PREZZO_BIGLIETTO             NUMBER (6,2)  NOT NULL , 
     NOME_PASSEGGERO              VARCHAR2 (100)  NOT NULL , 
     DATA_UTILIZZO                TIMESTAMP , 
     POSTO_DISABILE               NUMBER (1)  NOT NULL ,
     ID_CORSA 	  	  	  NUMBER (10) NOT NULL ,

     CONSTRAINT PK_BIGLIETTI PRIMARY KEY ( CODICE_BIGLIETTO ) ,
     CONSTRAINT UNIQUE_NUMERO_POSTO UNIQUE ( NUMERO_POSTO ) ,
     CONSTRAINT CHK_BIGLIETTI_PREZZO CHECK (PREZZO_BIGLIETTO > 0), 
     CONSTRAINT CHK_POSTO_DISABILE CHECK (POSTO_DISABILE in (0, 1)),
     CONSTRAINT FK_PRENOTAZIONE FOREIGN KEY ( PRENOTAZIONI_ID_PRENOTAZIONE ) 
	REFERENCES PRENOTAZIONI ( ID_PRENOTAZIONE ) ,

     ) LOGGING 
;


--TABELLA CITTA'
CREATE TABLE CITTA 
    ( 
     NOME       VARCHAR2 (50)  NOT NULL , 
     SIGLA_PROV VARCHAR2 (2)  NOT NULL ,

     CONSTRAINT CITTA_PK PRIMARY KEY ( NOME, SIGLA_PROV ) ,
     CONSTRAINT UNIQUE_SIGLA UNIQUE ( SIGLA_PROV )
    ) LOGGING 
;


CREATE TABLE CORSE 
    ( 
     ID_CORSA                   NUMBER (10) DEFAULT SEQ_CORSE.NEXTVAL  NOT NULL , 
     TRATTE_ID_TRATTA           NUMBER (10)  NOT NULL , 
     VEICOLI_ID_VEICOLO         NUMBER (10)  NOT NULL , 
     AUTISTI_ID_AUTISTA         NUMBER (10)  NOT NULL , 
     DATA_PARTENZA              DATE  NOT NULL , 
     ORARIO_PARTENZA            DATE  NOT NULL , 
     DURATA_CORSA               DATE  NOT NULL , 
     ORARIO_ARRIVO              DATE  NOT NULL , 
     STATO_CORSA                VARCHAR2 (20) DEFAULT 'PROGRAMMATA'  NOT NULL , 
     POSTI_DISPONIBILI          NUMBER (3)  NOT NULL , 
     POSTI_DISABILI_DISPONIBILI NUMBER (2) DEFAULT 2  NOT NULL , 

     CONSTRAINT PK_CORSE PRIMARY KEY ( ID_CORSA ) ,
     CONSTRAINT CHK_CORSE_ORARI CHECK ( ORARIO_ARRIVO > ORARIO_PARTENZA ) ,
     CONSTRAINT CHK_CORSE_POSTI_DISABILI_DISPONIBILI CHECK ( POSTI_DISABILI_DISPONIBILI >= 0 ) ,
     CONSTRAINT CHK_CORSE_POSTI_DISPONIBILI CHECK ( POSTI_DISPONIBILI >= 0 ) ,
     CONSTRAINT CHK_CORSE_STATO CHECK (STATO_CORSA IN ('PROGRAMMATA', 'IN_CORSO', 'COMPLETATA', 'CANCELLATA')) ,
     CONSTRAINT FK_CORSE_VEICOLO FOREIGN KEY ( VEICOLI_ID_VEICOLO ) 
    	REFERENCES VEICOLI ( ID_VEICOLO ) ,
     CONSTRAINT FK_CORSE_TRATTA FOREIGN KEY ( TRATTE_ID_TRATTA ) 
   	REFERENCES TRATTE ( ID_TRATTA ) ,
     CONSTRAINT FK_CORSE_AUTISTA FOREIGN KEY ( AUTISTI_ID_AUTISTA ) 
    	REFERENCES AUTISTI ( ID_DIPENDENTE ) 


    ) LOGGING 
;


CREATE TABLE FERMATE 
    ( 
     ID_FERMATA       NUMBER (10) DEFAULT SEQ_FERMATE.NEXTVAL  NOT NULL , 
     NOME             VARCHAR2 (100)  NOT NULL , 
     INDIRIZZO        VARCHAR2 (200)  NOT NULL , 
     CITTA_NOME       VARCHAR2 (50)  NOT NULL , 
     CITTA_SIGLA_PROV VARCHAR2 (2)  NOT NULL ,

     CONSTRAINT PK_FERMATE PRIMARY KEY ( ID_FERMATA ) ,
     CONSTRAINT FK_FERMATE_CITTA FOREIGN KEY ( CITTA_NOME, CITTA_SIGLA_PROV ) 
    	REFERENCES CITTA ( NOME, SIGLA_PROV ) 
 
    ) LOGGING 
;

CREATE TABLE METODI_PAGAMENTO 
    ( 
     ID_METODO   VARCHAR2 (2) NOT NULL , 
     NOME_METODO VARCHAR2 (20) NOT NULL ,

     CONSTRAINT METODI_PAGAMENTO_PK PRIMARY KEY ( ID_METODO ) 
    ) LOGGING 
;


CREATE TABLE PAGAMENTI 
    ( 
     ID_PAGAMENTO                 NUMBER (10) DEFAULT SEQ_PAGAMENTI.NEXTVAL  NOT NULL , 
     PRENOTAZIONI_ID_PRENOTAZIONE NUMBER (10)  NOT NULL , 
     METODI_PAGAMENTO_ID_METODO   VARCHAR2 (2)  NOT NULL , 
     IMPORTO                      NUMBER (8,2)  NOT NULL , 
     STATO_PAGAMENTO              VARCHAR2 (15) DEFAULT 'IN_CORSO'  NOT NULL , 
     DATA_PAGAMENTO               TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL ,

     CONSTRAINT PK_PAGAMENTI PRIMARY KEY ( ID_PAGAMENTO ) ,
     CONSTRAINT CHK_PAGAMENTI_IMPORTO CHECK (IMPORTO > 0) ,
     CONSTRAINT CHK_PAGAMENTI_STATO CHECK (STATO_PAGAMENTO IN ('COMPLETATO', 'FALLITO', 'IN_CORSO')) ,
     CONSTRAINT PAGAMENTI_PRENOTAZIONI_FK FOREIGN KEY ( PRENOTAZIONI_ID_PRENOTAZIONE ) 
    	REFERENCES PRENOTAZIONI ( ID_PRENOTAZIONE ) ,
     CONSTRAINT FK_PAGAMENTI_METODO FOREIGN KEY ( METODI_PAGAMENTO_ID_METODO ) 
    	REFERENCES METODI_PAGAMENTO ( ID_METODO )  

    ) LOGGING 
;

CREATE TABLE PRENOTAZIONI 
    ( 
     ID_PRENOTAZIONE             NUMBER (10) DEFAULT SEQ_PRENOTAZIONI.NEXTVAL  NOT NULL , 
     UTENTI_ID_UTENTE            NUMBER (10)  NOT NULL , 
     CORSE_ID_CORSA              NUMBER (10)  NOT NULL , 
     DATA_PRENOTAZIONE           TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     DATA_TRANSAZIONE_COMPLETATA TIMESTAMP , 
     NUMERO_BIGLIETTI            NUMBER (2)  NOT NULL , 
     NUMERO_BIGLIETTI_DISABILI   NUMBER (2) DEFAULT 0  NOT NULL , 
     PREZZO_TOTALE               NUMBER (8,2)  NOT NULL , 
     STATO_PRENOTAZIONE          VARCHAR2 (25) DEFAULT 'IN_ATTESA_PAGAMENTO'  NOT NULL , 
     ID_TRANSAZIONE              NUMBER (10)  NOT NULL , 

     CONSTRAINT PRENOTAZIONI_PK PRIMARY KEY ( ID_PRENOTAZIONE ) ,
     CONSTRAINT CHK_PRENOTAZIONI_BIGLIETTI_DISABILI CHECK (NUMERO_BIGLIETTI_DISABILI <= NUMERO_BIGLIETTI) ,
     CONSTRAINT CHK_PRENOTAZIONI_DATA_TRANSAZIONE CHECK (DATA_TRANSAZIONE_COMPLETATA IS NULL OR DATA_TRANSAZIONE_COMPLETATA >= DATA_PRENOTAZIONE) ,
     CONSTRAINT CHK_PRENOTAZIONI_NUMERO_BIGLIETTI CHECK (NUMERO_BIGLIETTI > 0) ,
     CONSTRAINT CHK_PRENOTAZIONI_STATO CHECK (STATO_PRENOTAZIONE IN ('IN_ATTESA_PAGAMENTO', 'CONFERMATA', 'ANNULLATA', 'INIZIALIZZATA', 'COMPLETATA')) ,
     CONSTRAINT FK_PRENOTAZIONI_UTENTE FOREIGN KEY ( UTENTI_ID_UTENTE ) 
    	REFERENCES UTENTI ( ID_UTENTE ) ,
     CONSTRAINT FK_PRENOTAZIONI_CORSA FOREIGN KEY ( CORSE_ID_CORSA ) 
   	 REFERENCES CORSE ( ID_CORSA ) 


    ) LOGGING 
;

CREATE TABLE TRATTE 
    ( 
     ID_TRATTA           NUMBER (10) DEFAULT SEQ_TRATTE.NEXTVAL  NOT NULL , 
     ID_FERMATA_PARTENZA NUMBER (10)  NOT NULL , 
     ID_FERMATA_ARRIVO   NUMBER (10)  NOT NULL , 
     PREZZO_BASE         NUMBER (6,2)  NOT NULL ,

     CONSTRAINT PK_TRATTE PRIMARY KEY ( ID_TRATTA ) ,
     CONSTRAINT CHK_TRATTE_DIVERSE CHECK (ID_FERMATA_PARTENZA != ID_FERMATA_ARRIVO) ,
     CONSTRAINT CHK_TRATTE_PREZZO CHECK (PREZZO_BASE > 0) ,
     CONSTRAINT TRATTE_FERMATE_FK FOREIGN KEY ( ID_FERMATA_PARTENZA ) 
    	REFERENCES FERMATE ( ID_FERMATA ) ,
     CONSTRAINT FK_TRATTE_ARRIVO FOREIGN KEY ( ID_FERMATA_ARRIVO ) 
    	REFERENCES FERMATE ( ID_FERMATA ) 
 
    ) LOGGING 
;


CREATE TABLE UTENTI 
    ( 
     ID_UTENTE          NUMBER (10) DEFAULT SEQ_UTENTI.NEXTVAL  NOT NULL , 
     NOME               VARCHAR2 (50)  NOT NULL , 
     COGNOME            VARCHAR2 (50)  NOT NULL , 
     DATA_NASCITA       DATE  NOT NULL , 
     EMAIL              VARCHAR2 (100)  NOT NULL , 
     TELEFONO           VARCHAR2 (15)  NOT NULL , 
     DATA_REGISTRAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
     INDIRIZZO          VARCHAR2 (100)  NOT NULL , 
 

     CONSTRAINT PK_UTENTI PRIMARY KEY ( ID_UTENTE ) ,
     CONSTRAINT UNIQUE_EMAIL UNIQUE ( EMAIL ) 
    ) LOGGING 
;

CREATE TABLE VEICOLI 
    ( 
     ID_VEICOLO            NUMBER (10) DEFAULT SEQ_VEICOLI.NEXTVAL  NOT NULL , 
     NOME_MODELLO          VARCHAR2 (30)  NOT NULL , 
     TARGA                 VARCHAR2 (10)  NOT NULL , 
     TELAIO                VARCHAR2 (17)  NOT NULL , 
     POSTI_TOTALI          NUMBER (3)  NOT NULL , 
     POSTI_DISABILI        NUMBER (2) DEFAULT 2  NOT NULL , 
     WIFI                  NUMBER (1) DEFAULT 0  NOT NULL , 
     CARICATORI            NUMBER (1) DEFAULT 0  NOT NULL , 
     DATA_IMMATRICOLAZIONE DATE  NOT NULL ,

     CONSTRAINT PK_VEICOLI PRIMARY KEY ( ID_VEICOLO ) ,
     CONSTRAINT CHK_VEICOLI_BOOLEAN_CARICATORI CHECK (CARICATORI IN (0, 1)) ,
     CONSTRAINT CHK_VEICOLI_BOOLEAN_WIFI CHECK (WIFI IN (0, 1)) ,
     CONSTRAINT CHK_VEICOLI_POSTI_DISABILI CHECK (POSTI_DISABILI <= POSTI_TOTALI) ,
     CONSTRAINT CHK_VEICOLI_POSTI_TOTALI CHECK (POSTI_TOTALI > 0) ,
     CONSTRAINT UNIQUE_VEICOLI_TARGA UNIQUE ( TARGA ) ,
     CONSTRAINT UNIQUE_VEICOLI_TELAIO UNIQUE ( TELAIO ) 

    ) LOGGING 
;


